name: sonic-client-web

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: login docker hub
        run: echo "${{ secrets.ACCESS_TOKEN_ALIYUN }}" | docker login --username=${{ secrets.ALIYUN_USERNAME }} registry.cn-hongkong.aliyuncs.com --password-stdin
      - name: build docker image
        run: docker build -f sonic-client-web/Dockerfile -t registry.cn-hongkong.aliyuncs.com/sonic-cloud/sonic-client-web-base:v1.0.0 .
      - name: push docker image
        run: docker push registry.cn-hongkong.aliyuncs.com/sonic-cloud/sonic-client-web-base:v1.0.0
